### ISSUE TITLE
after the last update the recorder stopped working for me

### ISSUE THREAD

**Issue by mytrntsite** [ChristianKnedel/DockerChaturbateRecorderGUI#33]
Hello, after the last update of the recorder it stopped working for me, I use it on my synology as a container, I have everything set up the same as before the update, however all online streams the recorder sees as offline

**Comment by ChristianKnedel** [comment]
Please pull all images new:
docker pull chrisknedel/chaturbate-recorder
docker pull chrisknedel/chaturbate-recorder-gui

**Comment by ChristianKnedel** [comment]
I also have the problem on my Synology diskstation and am working on a solution

**Comment by ChristianKnedel** [comment]
Please pull all images new
docker pull chrisknedel/chaturbate-recorder-gui:latest
docker pull chrisknedel/chaturbate-recorder:latest

**Comment by mytrntsite** [comment]
now the recorder works (shows onnline status) but new recordings do not show in the selected location.
in “ABSOLUTE_HOST_MEDIA” I specified “/code/database” alternating with “/volume1/docker/chaturbate” and it still doesn't work

**Comment by mytrntsite** [comment]
ok I found another strange problem, any link ending in “_” does not record in the application

**Comment by ChristianKnedel** [comment]
please check the limits in your "docker-compose.yml" file 
![Bildschirmfoto 2024-09-15 um 15 35 40](https://github.com/user-attachments/assets/2781c3b1-90c8-4093-8285-fb04931e001b)

**Comment by mytrntsite** [comment]
So yes, I did a fresh install, after installing one of the cameras in the list started recording, for a test I added a new camera to the list, which is also now onlinei, and this new one is not recording, I decided to reboot the container and after the reset neither of the online cameras is recording (both have offline status in the container, even though on the website both are online).

**Comment by sh23oopss** [comment]
> So yes, I did a fresh install, after installing one of the cameras in the list started recording, for a test I added a new camera to the list, which is also now onlinei, and this new one is not recording, I decided to reboot the container and after the reset neither of the online cameras is recording (both have offline status in the container, even though on the website both are online).

Hi, i have the exact same issues on Synology since the Update.

**Comment by Dethkiller15** [comment]
@ChristianKnedel 
I am sorry to hear that my implementations somehow borked the images for synology.

I ask that you attempt to test it on another system(raspberry Pi for example) and see if it works there. If it doesn't work on another system then the code was not implemented correctly in this repo, and I will update the code again in a branch.

**Comment by ChristianKnedel** [comment]
hi @mytrntsite ,
hi @sh23oopss  ,

please send me the “docker-compose” file. I could not find the problem on my diskstation yet

**Comment by sh23oopss** [comment]
@ChristianKnedel 

here is the one i am using:

---
version: '2'

services:    
  app:
    image: chrisknedel/chaturbate-recorder-gui:3.0
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      ABSOLUTE_HOST_MEDIA: "/volume1/x2/cbrecorder"
      LIMIT_MAXIMUM_FOLDER_GB: 20000 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: 'DockerAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chrisknedel/chaturbate-recorder:3.0'
      USER_UID: 1028
      USER_GID: 100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume2/docker/cbrec2:/code/database
    ports:
      - "8066:8000"
---

if i set it up as a new project and run it the first time, and add cams that are currently live, then they usually start to record. (not all, but most) but if they went off and back on again, it does not start to record anymore. also adding offline cams do not start to record if they go online.

before it was running for months, without any problems.

what i also noticed: 
preveiously the recorderapp-container  (cr_*) for each cam was starting periodicly to check if the cam is on, this does not happen anymore now.

at the moment i am playing around and trying to set up on raspberry pi, but it seems that i am to dumb for that ;-p

Thank you!

**Comment by sh23oopss** [comment]
forgot to mention: 
using :latest or :3.0 seems to behave the same

**Comment by ChristianKnedel** [comment]
Please pull all images new
docker pull chrisknedel/chaturbate-recorder-gui:latest

**Comment by sh23oopss** [comment]
That seems to work pretty well now!
Thank you!

**Comment by mytrntsite** [comment]
At me it still does not work, the situation is identical to the previous one, reinstalled one of the cameras has online status and seemingly records but there is no folder with the recording, after adding a new camera online no recording. In addition, the first working camera stops recording.version: '2'

services:
  app:
    image: chrisknedel/chaturbate-recorder-gui:latest
    container_name: recorder_app2
    restart: always
    environment:
      TZ: "Europe/Warsaw"
      ABSOLUTE_HOST_MEDIA: "/volume1/docker/chaturbate/"
      LIMIT_MAXIMUM_FOLDER_GB: 120 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 20 #or "0" to disable this limit
      COMMAND_ADAPTER: 'ShellAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chrisknedel/chaturbate-recorder'
      USER_UID: 0
      USER_GID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/chaturbate:/code/database
    ports:
      - "8081:8000"

I also changed the RECORDER_IMAGE: to 'chrisknedel/chaturbate-recorder' and "chrisknedel/chaturbate-recorder-gui:latest"

**Comment by Dethkiller15** [comment]
> what i also noticed: preveiously the recorderapp-container (cr_*) for each cam was starting periodicly to check if the cam is on, this does not happen anymore now.

I implemented a change in the code so that it does not need to launch a container just to see that a cam is offline. It does the same check in the main container now and because of how it does the check the code was changed to pass the cam url to the new container instead of the cam name. This was done to increase performance as creating containers is a bit costly in both RAM and CPU.

**Comment by Dethkiller15** [comment]
@mytrntsite have you tried building the image(s) using the instructions?

**Comment by Dethkiller15** [comment]
@mytrntsite While I am using a raspberry Pi 4 to record and am sending the recordings to my synology NAS via SMB here is my compose, modified to fit your settings.(dev adapter) also I suggest you change the file structure slightly. Just have recordings go to a recordings folder and the database ether in its own folder or directly in the dir.(or pass the .db file directly.)

```
#docker-compose.yml
version: '2'

services:    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recorder_app
    restart: always
    environment:
      TZ: "America/Chicogo"
      ABSOLUTE_HOST_MEDIA: "/volume1/docker/chaturbate/recordings/"
      LIMIT_MAXIMUM_FOLDER_GB: 2000000 # Had to set it like this cuz at one point in time it was not recording when I set to 0 and I am not going to change it.
      LIMIT_MAXIMUM_DOWNLOADS: 1000000 # same as above
      COMMAND_ADAPTER: 'DockerAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chatrubate-recorder'
      USER_ID: 0
      USER_GID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/chaturbate:/code/database
      #- /volume1/docker/chaturbate/db.sqlite3:/code/database/db.sqlite3 # example of passing the database file directly.
      #- ./interface/logs:/code/logs
    ports:
      - "8002:8000"
```

There could also be incorrect read and write perms if you are attempting to use it for the first time in the directory you set to record to.

chmod 755 -R /location/of/recordings
